version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8.1-fpm
        working_dir: /var/www
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        container_name: slim_app

    db:
        image: mysql:5.7.40
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: files_downloader
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: slim_db
